MKSHELL=$PLAN9/bin/rc

<$PLAN9/src/mkhdr

<../mkconfig

CFLAGS='-std=c99' -I$PREFIX/include
LDFLAGS=-L$PREFIX/lib -lhhset -lhhash

LIB=$PREFIX/lib/libhhmap.a

OFILES=\
	hhmap.$O\

CFILES=\
	hhmap.c\

HFILES=\
	hhmap.h\

<$PLAN9/src/mklib

install:QV:	$HFILES
	for (t in $HFILES)
    	cp $t $PREFIX/include
